# Generated by Django 3.1.5 on 2021-02-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='用户名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(default='', upload_to='avatar/')),
                ('sign', models.CharField(default='此时无声胜有声', max_length=80, verbose_name='个性签名')),
                ('location_province', models.CharField(default=' ', max_length=16, verbose_name='省份')),
                ('location_city', models.CharField(default=' ', max_length=22, verbose_name='城市')),
                ('gender', models.BooleanField(default=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('job', models.CharField(default=' ', max_length=20, verbose_name='职业')),
                ('last_news', models.IntegerField(default=0, verbose_name='上次访问时公开新闻类ID')),
                ('last_sports', models.IntegerField(default=0, verbose_name='上次访问时公开体育类ID')),
                ('last_science', models.IntegerField(default=0, verbose_name='上次访问时公开科学类ID')),
                ('last_entertain', models.IntegerField(default=0, verbose_name='上次访问时公开娱乐类ID')),
                ('last_literature', models.IntegerField(default=0, verbose_name='上次访问时公开文学类ID')),
                ('inform_comment', models.DateTimeField(verbose_name='上次查看评论我的时间')),
                ('inform_reply', models.DateTimeField(verbose_name='上次查看回复我的时间')),
                ('inform_up', models.DateTimeField(verbose_name='上次查看点赞我的时间')),
                ('inform_follow', models.DateTimeField(verbose_name='上次查看关注我的时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='账户创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'u_s_e_r',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.IntegerField(verbose_name='关注用户的ID')),
                ('as_friend_at', models.DateTimeField(auto_now_add=True, verbose_name='添加好友时间')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
