# Generated by Django 3.1.5 on 2021-02-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(max_length=9, primary_key=True, serialize=False, verbose_name='文章ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可查看')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('has_img', models.BooleanField(default=False, verbose_name='有无图片')),
                ('article_type', models.CharField(max_length=10, verbose_name='文章类型')),
                ('authority', models.BooleanField(default=False, verbose_name='文章权限')),
                ('introduce', models.CharField(max_length=90, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('last_rank', models.IntegerField(null=True, verbose_name='上次排名')),
                ('present_rank', models.IntegerField(null=True, verbose_name='本次排名')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_time', models.DateTimeField(auto_now_add=True)),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.AutoField(max_length=99, primary_key=True, serialize=False)),
                ('view_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'heat',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('comment_content', models.CharField(max_length=200, verbose_name='评论详情')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('_parent', models.BooleanField(default=0, verbose_name='评论类型')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('to_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_time'],
            },
        ),
    ]
