# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-01-18 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(max_length=9, primary_key=True, serialize=False, verbose_name='文章ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可查看')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('article_type', models.CharField(max_length=10, verbose_name='文章类型')),
                ('authority', models.BooleanField(default=False, verbose_name='文章权限')),
                ('introduce', models.CharField(max_length=90, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('comment_content', models.CharField(max_length=200, verbose_name='评论详情')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('_parent', models.BooleanField(default=0, verbose_name='评论类型')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('to_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
