# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-01-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210121_2304'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.AutoField(max_length=99, primary_key=True, serialize=False)),
                ('view_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'db_table': 'heat',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='has_img',
            field=models.BooleanField(default=False, verbose_name='有无图片'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_rank',
            field=models.IntegerField(null=True, verbose_name='上次排名'),
        ),
        migrations.AddField(
            model_name='article',
            name='present_rank',
            field=models.IntegerField(null=True, verbose_name='本次排名'),
        ),
        migrations.AddField(
            model_name='heat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AddField(
            model_name='heat',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
