# Generated by Django 3.1.5 on 2021-02-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_rank',
        ),
        migrations.RemoveField(
            model_name='article',
            name='present_rank',
        ),
    ]
