# Generated by Django 3.1.5 on 2021-02-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210205_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heat',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='heat',
            name='visitor',
        ),
        migrations.AlterField(
            model_name='comments',
            name='_parent',
            field=models.IntegerField(default=0, verbose_name='评论类型'),
        ),
        migrations.AlterField(
            model_name='heat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章标题'),
        ),
    ]
