# Generated by Django 3.1.5 on 2021-02-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210207_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stars',
        ),
    ]
