# Generated by Django 3.1.5 on 2021-02-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_comments__parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='has_img',
        ),
    ]
