# Generated by Django 3.1.5 on 2021-02-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     # name='avatar',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='inform_comment',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='inform_follow',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='inform_reply',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='inform_up',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_entertain',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_literature',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_news',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_science',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_sports',
        # ),
    ]
