# Generated by Django 3.1.5 on 2021-02-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210207_1338'),
    ]

    operations = [

    ]
