# Generated by Django 3.1.5 on 2021-02-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210208_1836'),
    ]

    operations = [

    ]
