# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-01-18 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='用户名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='账户创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'u_s_e_r',
            },
        ),
    ]
