# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-01-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_entertain',
            field=models.IntegerField(default=0, verbose_name='娱乐更新数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_literature',
            field=models.IntegerField(default=0, verbose_name='文学更新数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_news',
            field=models.IntegerField(default=0, verbose_name='新闻更新数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_science',
            field=models.IntegerField(default=0, verbose_name='科学更新数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_sports',
            field=models.IntegerField(default=0, verbose_name='体育更新数'),
        ),
    ]
